#!/bin/bash

help() { echo "gifrecorder [record|stop]"; }

notify() {
	notify-send --app-name="GifRecorder" "$1"
}

case "$1" in
	record|start)
		mkdir -p /tmp/gifrecorder
		touch /tmp/gifrecorder/.recording

		while [ -f /tmp/gifrecorder/.recording ]; do
			scrot -u "/tmp/gifrecorder/scrot_$(date +"%H_%M_%S_%N").png"
			sleep 0.2
		done
		;;

	stop)
		rm /tmp/gifrecorder/.recording
		notify "Record Ended, encoding frames"
		convert -delay 20 -loop 0 /tmp/gifrecorder/*.png /tmp/gifrecorder/animation.gif
		rm /tmp/gifrecorder/*.png
		mv /tmp/gifrecorder/animation.gif ~/animation.gif
		notify "Frames encoded, gif saved on ~/animation.gif"
		;;

	help|--help)
		help
		;;

	*)
		echo "Invalid argument"
		help
		;;
esac
