#!/bin/bash

help() { echo "gifrecorder [record|stop]"; }

notify() {
	notify-send --app-name="GifRecorder" "$1"
}

case "$1" in
	record|start)
		if ! mkdir /tmp/gifrecorder; then
			notify "Recording already in progress"
			echo "Recording already in progress" >&2
			exit 1
		fi

		while [ -d /tmp/gifrecorder ]; do
			scrot --pointer "/tmp/gifrecorder/scrot_$(date '+%s.N').png"
			sleep 0.2
		done
		;;

	stop)
		mv -T /tmp/gifrecorder /tmp/gifrecorder.$$
		date=$(date '+%F_%T.%N')
		notify "Record Ended, encoding frames"
		convert -delay 20 -loop 0 /tmp/gifrecorder.$$/*.png /tmp/gifrecorder.$$/animation.gif
		mv /tmp/gifrecorder.$$/animation.gif ~/"gifrecord_$date.gif"
		rm -rf /tmp/gifrecorder.$$
		notify "Frames encoded, gif saved on ~/gifrecord_$date.gif"
		;;

	help|--help)
		help
		;;

	*)
		echo "Invalid argument"
		help
		;;
esac
